# Data
data_file: "data/filtered_data_${predictor}.parquet"
num_workers: 4
min_prevalence: 0.01
min_cases: 0.1
eps_prevalence: 1.0e-5
use_cyclical_time: true
use_existing_split: false
split_file: "data/split_${predictor}.json"

# Model
d_model: 128
n_layers: 4
d_state: 64 # TODO: try 128 too?
d_conv: 4
expand: 2
head_dim: 64
chunk_size: 256
output_dim: 1
dropout: 0.025

# Hyperparameters
weight_decay: 1e-2
lr: 3e-4
batch_size: 256
num_epochs: 100
patience: 5
diff_loss_alpha: 0.05

# Checkpointing
checkpoint_dir: "${output_dir}/checkpoints"
restore_checkpoint: false
max_checkpoints_to_keep: 3

# General
predictor: prevalence # prevalence | cases
seed: 42
loss_method: stateMINT.training.loss.weighted_mse
use_wandb: false
output_dir: "train_outputs/${predictor}"
wandb:
  project: "stateMINT"
  name: "train-${predictor}-1"