defaults:
  - _self_ # Load current and override with the following defaults
  - target: prevalence

# Data
data_file: "data/filtered_data_${predictor}.parquet"
split_file: "data/split_${predictor}.json"
num_workers: 0
use_existing_split: false
eps_prevalence: 1.0e-5

# Model
loss_method: stateMINT.training.loss.weighted_mse
n_layers: 4
d_conv: 4
expand: 2
head_dim: 64
chunk_size: 256
output_dim: 1
d_model: 256
d_state: 128

# Hyperparameters
num_epochs: 200
min_epochs: 100
patience: 50
diff_loss_alpha: 0.05
lr: 1e-3
batch_size: 128
dropout: 0.3
weight_decay: 1e-4

# Checkpointing
checkpoint_dir: "${output_dir}/ckpts-${cur_time}"
restore_checkpoint: false
max_checkpoints_to_keep: 1

# General
cur_time: ${now:%Y-%m-%dT%H:%M:%S}
seed: 42
use_wandb: false
output_dir: "train_outputs/${predictor}"
wandb:
  project: "stateMINT-${predictor}"
  name: "train-${predictor}-${cur_time}"